### ISSUE TITLE
Interface for GPU

### ISSUE THREAD

**Issue by haoyangz** [kuz/caffe-with-spearmint#3]
If I understand  the [code](https://github.com/kuz/caffe-with-spearmint/blob/master/cwsm/cafferun.py#L73) correctly , currently it would only run on CPU.  It would be nice and necessary for run.py to accept an optional parameter that specifies the GPU number and to run the code on the corresponding GPU.

**Comment by kuz** [comment]
Caffe runs on both GPU or CPU. It is specified in your `solver.prototxt`. See for example the [line](https://github.com/kuz/caffe-with-spearmint/blob/master/experiments/mnist/model/solver.prototxt#L16) from the the default MNIST experiment. CWSM only starts the Caffe instances (which run on GPU), so for CWSM itself CPU is enough.

**Comment by haoyangz** [comment]
Right, I understand. But in our case we have several GPUs in the lab and we usually use "--gpu 2" for example to specify which GPU it should run so that people in the lab don't interference with each other. It's a minor feature though, I admit.

**Comment by kuz** [comment]
Ah, I see now. You can use `gpu: 2` as a parameter in the `solver.prototxt`.

**Comment by haoyangz** [comment]
Hm, I didn't know I could specify it in solver.txt. Thanks! And it should actually be `device_id : 2`
