### ISSUE TITLE
Multiple variables are getting mapped to OPTIMIZE_std_1? (instead of _2, _3, ...)

### ISSUE THREAD

**Issue by forresti** [kuz/caffe-with-spearmint#4]
I've successfully run the caffe-with-spearmint MNIST example, and now I'm moving toward using caffe-with-spearmint for my own application. Right now, I'm interested in optimizing the standard deviation (`std`) of the weight initialization in a Network-in-Network. 

Let me walk you through where things are going wrong...

1) I set up my `model/trainval.prototxt` with two `std` fields filled in like this:
      `std: OPTIMIZE{"type":"FLOAT", "min": 0.005, "max": 0.05}`

2) In `tmp/template_trainval.prototxt`, these _both_ get mapped to `OPTIMIZE_std_1`:

```
layer {name: "conv1"
     convolution_param {weight_filler{ std: OPTIMIZE_std_1 } }
}
layer {name: "cccp1"
     convolution_param {weight_filler{ std: OPTIMIZE_std_1 } } ##(should be OPTIMIZE_std_2)
}
```

This is odd, because in the MNIST example, I see that optimizing `kernel_size` in multiple layers maps to `OPTIMIZE_kernel_size_1`, `OPTIMIZE_kernel_size_2`, and `OPTIMIZE_kernel_size_3`.

3) As a result of having two fields that are both OPTIMIZE_kernel_size_1, `tmp/<datetime>_trainval.prototxt` filled in with an optimized value for conv1, but it still OPTIMIZE_std_1 for the next convolutional layer:

```
layer {name: "conv1"
     convolution_param {weight_filler{ std: 0.005 } }
}
layer {name: "cccp1"
     convolution_param {weight_filler{ std: OPTIMIZE_std_1 } }
}
```

4) Caffe naturally doesn't understand what to do with `std: OPTIMIZE_std_1`, so it fails to run training.

**Any ideas why caffe-with-spearmint isn't filling in `OPTIMIZE_std_2` in the 2nd convolutional layer's `std` field?**

I put all samples of all 3 files (models/trainval.prototxt, tmp/template_trainval.prototxt, and tmp/datetime_trainval.prototxt) in a gist here:
https://gist.github.com/forresti/138d8bb79457a1146607

**Comment by kuz** [comment]
Should work now, give it a try.

**Comment by forresti** [comment]
That worked! Thanks a lot!
