### ISSUE TITLE
Use HDF5 data instead of LMDB

### ISSUE THREAD

**Issue by avalada** [kuz/caffe-with-spearmint#9]
Hi @kuz,

Is there a way to use HDF5 data instead of LMDB? Cant see any explicit checks for the LMDB, other than the presence of the folders. Would it be enough to just put the HDF5 files in the train_lmdb and val_lmdb folders and mention the type as "HDF5Data" in the net prototxt?

Thanks!

**Comment by kuz** [comment]
I would imagine that yes, just specify the locations and configure .prototxt accordingly.

**Comment by HighPerformance01** [comment]
Hi @kuz,

The tool looks great, thank you for that. But as soon as I try to use HDF5, it does not seems to work. I tried to change the locations, prototxt and even run.py but still I got the following error:

---------------------------------------------------------------------------------------------------------------------------

Running python job.
Changed into dir /home/test01/caffe-with-spearmint-master/experiments/mnist3/spearmint
Importing cafferun.py
Running cafferun.main()
Got result None
Traceback (most recent call last):
  File "/home/test01/Spearmint-master/spearmint/launcher.py", line 256, in launch
    if np.isnan(result):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Problem executing the function
Job failed in 0.90 seconds.
{u'base_lr_1': array([  1.00000000e-05]), u'momentum_1': array([ 0.8]), u'weight_decay_1': array([ 0.0001])}
CAFFE RETURN CODE 134
-----------------------------
2016-15-05-16-47-10 None
-----------------------------
(<type 'exceptions.TypeError'>, TypeError("ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''",), <traceback object at 0x7f736c
c84488>)

---------------------------------------------------------------------------------------------------------------------------

do you know what should be change to get that working?
